### ISSUE TITLE
Missing Surat in the database 

### ISSUE THREAD

**Issue by ghost** [nabilashraf/cities1000#1]
https://en.wikipedia.org/wiki/Surat

Is there a workaround for this?

**Comment by zeke** [comment]
The process by which data is gathered from geonames.org and added to this repo is not described. Ideally there would be an `npm run build` script to download the latest data and produce a new version of the data file.

That said, the source data in the GeoNames project might be missing Surat as well. @georgebatalinski I would suggest looking there to see if it's included.

**Comment by nabilashraf** [comment]
Hi @georgebatalinski , I've updated the package with latest data from geonames. You can run the build command as mentioned by @zeke and you will have the latest data to use with in your code. However, I did see that the mentioned city was in the earlier file as well. But anyways , all updated so it should be good to go.

**Comment by nabilashraf** [comment]
@zeke Created a pull request for the changes made here to reflect on main package.
